// ------------------------------------------------------------------------------
//  <auto-generated>
//      此代码由编码的 UI 测试生成器生成。
//      版本: 14.0.0.0
//
//      如果重新生成代码，则更改此文件可能会导致错误的行为，
//      并将丢失这些更改。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace posui
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UI主菜单选择Window UI主菜单选择Window
        {
            get
            {
                if ((this.mUI主菜单选择Window == null))
                {
                    this.mUI主菜单选择Window = new UI主菜单选择Window();
                }
                return this.mUI主菜单选择Window;
            }
        }
        
        public UI收银员登录Window UI收银员登录Window
        {
            get
            {
                if ((this.mUI收银员登录Window == null))
                {
                    this.mUI收银员登录Window = new UI收银员登录Window();
                }
                return this.mUI收银员登录Window;
            }
        }
        #endregion
        
        #region Fields
        private UI主菜单选择Window mUI主菜单选择Window;
        
        private UI收银员登录Window mUI收银员登录Window;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI主菜单选择Window : WinWindow
    {
        
        public UI主菜单选择Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "主菜单选择";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("主菜单选择");
            #endregion
        }
        
        #region Properties
        public 主菜单选择 主菜单选择
        {
            get
            {
                if ((this.m主菜单选择 == null))
                {
                    this.m主菜单选择 = new 主菜单选择(this);
                }
                return this.m主菜单选择;
            }
        }
        #endregion
        
        #region Fields
        private 主菜单选择 m主菜单选择;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class 主菜单选择 : WinClient
    {
        
        public 主菜单选择(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinControl.PropertyNames.Name] = "none";
            this.WindowTitles.Add("主菜单选择");
            #endregion
        }
        
        #region Properties
        public WinEdit 前台收银
        {
            get
            {
                if ((this.m前台收银 == null))
                {
                    this.m前台收银 = new WinEdit(this);
                    #region 搜索条件
                    this.m前台收银.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m前台收银.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m前台收银;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit m前台收银;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI收银员登录Window : WinWindow
    {
        
        public UI收银员登录Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "收银员登录";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("收银员登录");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1002";
            this.WindowTitles.Add("收银员登录");
            #endregion
        }
        
        #region Properties
        public WinEdit 收银员编码
        {
            get
            {
                if ((this.m收银员编码 == null))
                {
                    this.m收银员编码 = new WinEdit(this);
                    #region 搜索条件
                    this.m收银员编码.WindowTitles.Add("收银员登录");
                    #endregion
                }
                return this.m收银员编码;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit m收银员编码;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1003";
            this.WindowTitles.Add("收银员登录");
            #endregion
        }
        
        #region Properties
        public WinEdit 收银员密码
        {
            get
            {
                if ((this.m收银员密码 == null))
                {
                    this.m收银员密码 = new WinEdit(this);
                    #region 搜索条件
                    this.m收银员密码.WindowTitles.Add("收银员登录");
                    #endregion
                }
                return this.m收银员密码;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit m收银员密码;
        #endregion
    }
}
