// ------------------------------------------------------------------------------
//  <auto-generated>
//      此代码由编码的 UI 测试生成器生成。
//      版本: 14.0.0.0
//
//      如果重新生成代码，则更改此文件可能会导致错误的行为，
//      并将丢失这些更改。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace posui
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UI主菜单选择Window UI主菜单选择Window
        {
            get
            {
                if ((this.mUI主菜单选择Window == null))
                {
                    this.mUI主菜单选择Window = new UI主菜单选择Window();
                }
                return this.mUI主菜单选择Window;
            }
        }
        
        public UI收银员登录Window UI收银员登录Window
        {
            get
            {
                if ((this.mUI收银员登录Window == null))
                {
                    this.mUI收银员登录Window = new UI收银员登录Window();
                }
                return this.mUI收银员登录Window;
            }
        }
        
        public UI当班Window1 UI当班Window1
        {
            get
            {
                if ((this.mUI当班Window1 == null))
                {
                    this.mUI当班Window1 = new UI当班Window1();
                }
                return this.mUI当班Window1;
            }
        }
        
        public UI提示信息Window UI提示信息Window
        {
            get
            {
                if ((this.mUI提示信息Window == null))
                {
                    this.mUI提示信息Window = new UI提示信息Window();
                }
                return this.mUI提示信息Window;
            }
        }
        
        public UI畅捷通T零售POS软件Window UI畅捷通T零售POS软件Window
        {
            get
            {
                if ((this.mUI畅捷通T零售POS软件Window == null))
                {
                    this.mUI畅捷通T零售POS软件Window = new UI畅捷通T零售POS软件Window();
                }
                return this.mUI畅捷通T零售POS软件Window;
            }
        }
        
        public UI服务器连接设置Window UI服务器连接设置Window
        {
            get
            {
                if ((this.mUI服务器连接设置Window == null))
                {
                    this.mUI服务器连接设置Window = new UI服务器连接设置Window();
                }
                return this.mUI服务器连接设置Window;
            }
        }
        
        public UI选择账套Window UI选择账套Window
        {
            get
            {
                if ((this.mUI选择账套Window == null))
                {
                    this.mUI选择账套Window = new UI选择账套Window();
                }
                return this.mUI选择账套Window;
            }
        }
        
        public UI交班Window UI交班Window
        {
            get
            {
                if ((this.mUI交班Window == null))
                {
                    this.mUI交班Window = new UI交班Window();
                }
                return this.mUI交班Window;
            }
        }
        
        public UI收银界面esc菜单选择Window UI收银界面esc菜单选择Window
        {
            get
            {
                if ((this.mUI收银界面esc菜单选择Window == null))
                {
                    this.mUI收银界面esc菜单选择Window = new UI收银界面esc菜单选择Window();
                }
                return this.mUI收银界面esc菜单选择Window;
            }
        }
        
        public UI请输入新数量Window UI请输入新数量Window
        {
            get
            {
                if ((this.mUI请输入新数量Window == null))
                {
                    this.mUI请输入新数量Window = new UI请输入新数量Window();
                }
                return this.mUI请输入新数量Window;
            }
        }
        
        public UI现金结算Window UI现金结算Window
        {
            get
            {
                if ((this.mUI现金结算Window == null))
                {
                    this.mUI现金结算Window = new UI现金结算Window();
                }
                return this.mUI现金结算Window;
            }
        }
        #endregion
        
        #region Fields
        private UI主菜单选择Window mUI主菜单选择Window;
        
        private UI收银员登录Window mUI收银员登录Window;
        
        private UI当班Window1 mUI当班Window1;
        
        private UI提示信息Window mUI提示信息Window;
        
        private UI畅捷通T零售POS软件Window mUI畅捷通T零售POS软件Window;
        
        private UI服务器连接设置Window mUI服务器连接设置Window;
        
        private UI选择账套Window mUI选择账套Window;
        
        private UI交班Window mUI交班Window;
        
        private UI收银界面esc菜单选择Window mUI收银界面esc菜单选择Window;
        
        private UI请输入新数量Window mUI请输入新数量Window;
        
        private UI现金结算Window mUI现金结算Window;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI主菜单选择Window : WinWindow
    {
        
        public UI主菜单选择Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "主菜单选择";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("主菜单选择");
            #endregion
        }
        
        #region Properties
        public 主菜单选择 主菜单选择
        {
            get
            {
                if ((this.m主菜单选择 == null))
                {
                    this.m主菜单选择 = new 主菜单选择(this);
                }
                return this.m主菜单选择;
            }
        }
        #endregion
        
        #region Fields
        private 主菜单选择 m主菜单选择;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class 主菜单选择 : WinClient
    {
        
        public 主菜单选择(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinControl.PropertyNames.Name] = "none";
            this.WindowTitles.Add("主菜单选择");
            #endregion
        }
        
        #region Properties
        public WinEdit 前台收银
        {
            get
            {
                if ((this.m前台收银 == null))
                {
                    this.m前台收银 = new WinEdit(this);
                    #region 搜索条件
                    this.m前台收银.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m前台收银.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m前台收银;
            }
        }
        
        public WinEdit 当班
        {
            get
            {
                if ((this.m当班 == null))
                {
                    this.m当班 = new WinEdit(this);
                    #region 搜索条件
                    this.m当班.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m当班.SearchProperties[WinEdit.PropertyNames.Instance] = "2";
                    this.m当班.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m当班;
            }
        }
        
        public WinEdit 交班
        {
            get
            {
                if ((this.m交班 == null))
                {
                    this.m交班 = new WinEdit(this);
                    #region 搜索条件
                    this.m交班.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m交班.SearchProperties[WinEdit.PropertyNames.Instance] = "3";
                    this.m交班.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m交班;
            }
        }
        
        public WinEdit 练习收银
        {
            get
            {
                if ((this.m练习收银 == null))
                {
                    this.m练习收银 = new WinEdit(this);
                    #region 搜索条件
                    this.m练习收银.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m练习收银.SearchProperties[WinEdit.PropertyNames.Instance] = "4";
                    this.m练习收银.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m练习收银;
            }
        }
        
        public WinEdit 参数设置
        {
            get
            {
                if ((this.m参数设置 == null))
                {
                    this.m参数设置 = new WinEdit(this);
                    #region 搜索条件
                    this.m参数设置.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m参数设置.SearchProperties[WinEdit.PropertyNames.Instance] = "5";
                    this.m参数设置.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m参数设置;
            }
        }
        
        public WinEdit 日结
        {
            get
            {
                if ((this.m日结 == null))
                {
                    this.m日结 = new WinEdit(this);
                    #region 搜索条件
                    this.m日结.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m日结.SearchProperties[WinEdit.PropertyNames.Instance] = "6";
                    this.m日结.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m日结;
            }
        }
        
        public WinEdit 明细查询
        {
            get
            {
                if ((this.m明细查询 == null))
                {
                    this.m明细查询 = new WinEdit(this);
                    #region 搜索条件
                    this.m明细查询.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m明细查询.SearchProperties[WinEdit.PropertyNames.Instance] = "7";
                    this.m明细查询.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m明细查询;
            }
        }
        
        public WinEdit 数据同步
        {
            get
            {
                if ((this.m数据同步 == null))
                {
                    this.m数据同步 = new WinEdit(this);
                    #region 搜索条件
                    this.m数据同步.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m数据同步.SearchProperties[WinEdit.PropertyNames.Instance] = "8";
                    this.m数据同步.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m数据同步;
            }
        }
        
        public WinEdit 修改密码
        {
            get
            {
                if ((this.m修改密码 == null))
                {
                    this.m修改密码 = new WinEdit(this);
                    #region 搜索条件
                    this.m修改密码.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m修改密码.SearchProperties[WinEdit.PropertyNames.Instance] = "9";
                    this.m修改密码.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m修改密码;
            }
        }
        
        public WinEdit 重新登录
        {
            get
            {
                if ((this.m重新登录 == null))
                {
                    this.m重新登录 = new WinEdit(this);
                    #region 搜索条件
                    this.m重新登录.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m重新登录.SearchProperties[WinEdit.PropertyNames.Instance] = "10";
                    this.m重新登录.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m重新登录;
            }
        }
        
        public WinEdit 退出系统
        {
            get
            {
                if ((this.m退出系统 == null))
                {
                    this.m退出系统 = new WinEdit(this);
                    #region 搜索条件
                    this.m退出系统.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m退出系统.SearchProperties[WinEdit.PropertyNames.Instance] = "11";
                    this.m退出系统.WindowTitles.Add("主菜单选择");
                    #endregion
                }
                return this.m退出系统;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit m前台收银;
        
        private WinEdit m当班;
        
        private WinEdit m交班;
        
        private WinEdit m练习收银;
        
        private WinEdit m参数设置;
        
        private WinEdit m日结;
        
        private WinEdit m明细查询;
        
        private WinEdit m数据同步;
        
        private WinEdit m修改密码;
        
        private WinEdit m重新登录;
        
        private WinEdit m退出系统;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI收银员登录Window : WinWindow
    {
        
        public UI收银员登录Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "收银员登录";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("收银员登录");
            #endregion
        }
        
        #region Properties
        public UI收银员子Window UI收银员子Window
        {
            get
            {
                if ((this.mUI收银员子Window == null))
                {
                    this.mUI收银员子Window = new UI收银员子Window(this);
                }
                return this.mUI收银员子Window;
            }
        }
        
        public UI收银员登录子Window1 UI收银员登录子Window1
        {
            get
            {
                if ((this.mUI收银员登录子Window1 == null))
                {
                    this.mUI收银员登录子Window1 = new UI收银员登录子Window1(this);
                }
                return this.mUI收银员登录子Window1;
            }
        }
        #endregion
        
        #region Fields
        private UI收银员子Window mUI收银员子Window;
        
        private UI收银员登录子Window1 mUI收银员登录子Window1;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI收银员子Window : WinWindow
    {
        
        public UI收银员子Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1002";
            this.WindowTitles.Add("收银员登录");
            #endregion
        }
        
        #region Properties
        public WinEdit 收银员编码
        {
            get
            {
                if ((this.m收银员编码 == null))
                {
                    this.m收银员编码 = new WinEdit(this);
                    #region 搜索条件
                    this.m收银员编码.WindowTitles.Add("收银员登录");
                    #endregion
                }
                return this.m收银员编码;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit m收银员编码;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI收银员登录子Window1 : WinWindow
    {
        
        public UI收银员登录子Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1003";
            this.WindowTitles.Add("收银员登录");
            #endregion
        }
        
        #region Properties
        public WinEdit 收银员密码
        {
            get
            {
                if ((this.m收银员密码 == null))
                {
                    this.m收银员密码 = new WinEdit(this);
                    #region 搜索条件
                    this.m收银员密码.WindowTitles.Add("收银员登录");
                    #endregion
                }
                return this.m收银员密码;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit m收银员密码;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI当班Window1 : WinWindow
    {
        
        public UI当班Window1()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "当班";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("当班");
            #endregion
        }
        
        #region Properties
        public UI当班子Window UI当班子Window
        {
            get
            {
                if ((this.mUI当班子Window == null))
                {
                    this.mUI当班子Window = new UI当班子Window(this);
                }
                return this.mUI当班子Window;
            }
        }
        
        public UI标题Window UI标题Window
        {
            get
            {
                if ((this.mUI标题Window == null))
                {
                    this.mUI标题Window = new UI标题Window(this);
                }
                return this.mUI标题Window;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UI当班子Window mUI当班子Window;
        
        private UI标题Window mUI标题Window;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI当班子Window : WinWindow
    {
        
        public UI当班子Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1005";
            this.WindowTitles.Add("当班");
            #endregion
        }
        
        #region Properties
        public WinComboBox UI班次选择控件
        {
            get
            {
                if ((this.mUI班次选择控件 == null))
                {
                    this.mUI班次选择控件 = new WinComboBox(this);
                    #region 搜索条件
                    this.mUI班次选择控件.WindowTitles.Add("当班");
                    #endregion
                }
                return this.mUI班次选择控件;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUI班次选择控件;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI标题Window : WinWindow
    {
        
        public UI标题Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1000";
            this.WindowTitles.Add("当班");
            #endregion
        }
        
        #region Properties
        public WinText UI标题Text
        {
            get
            {
                if ((this.mUI标题Text == null))
                {
                    this.mUI标题Text = new WinText(this);
                    #region 搜索条件
                    this.mUI标题Text.SearchProperties[WinText.PropertyNames.Name] = "当班";
                    this.mUI标题Text.WindowTitles.Add("当班");
                    #endregion
                }
                return this.mUI标题Text;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUI标题Text;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1004";
            this.WindowTitles.Add("当班");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("当班");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI提示信息Window : WinWindow
    {
        
        public UI提示信息Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "提示信息";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("提示信息");
            #endregion
        }
        
        #region Properties
        public WinClient UI提示信息窗口有后续流程Client
        {
            get
            {
                if ((this.mUI提示信息窗口有后续流程Client == null))
                {
                    this.mUI提示信息窗口有后续流程Client = new WinClient(this);
                    #region 搜索条件
                    this.mUI提示信息窗口有后续流程Client.SearchProperties[WinControl.PropertyNames.Name] = "提示信息";
                    this.mUI提示信息窗口有后续流程Client.WindowTitles.Add("提示信息");
                    #endregion
                }
                return this.mUI提示信息窗口有后续流程Client;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUI提示信息窗口有后续流程Client;
        
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1002";
            this.WindowTitles.Add("提示信息");
            #endregion
        }
        
        #region Properties
        public WinText UI是否手工下载数据Text
        {
            get
            {
                if ((this.mUI是否手工下载数据Text == null))
                {
                    this.mUI是否手工下载数据Text = new WinText(this);
                    #region 搜索条件
                    this.mUI是否手工下载数据Text.SearchProperties[WinText.PropertyNames.Name] = "是否手工下载数据？";
                    this.mUI是否手工下载数据Text.WindowTitles.Add("提示信息");
                    #endregion
                }
                return this.mUI是否手工下载数据Text;
            }
        }
        
        public WinText UI确认交班吗Text
        {
            get
            {
                if ((this.mUI确认交班吗Text == null))
                {
                    this.mUI确认交班吗Text = new WinText(this);
                    #region 搜索条件
                    this.mUI确认交班吗Text.SearchProperties[WinText.PropertyNames.Name] = "确认交班吗？";
                    this.mUI确认交班吗Text.WindowTitles.Add("提示信息");
                    #endregion
                }
                return this.mUI确认交班吗Text;
            }
        }
        
        public WinText UI确认退出畅捷通T零售POS软件吗Text
        {
            get
            {
                if ((this.mUI确认退出畅捷通T零售POS软件吗Text == null))
                {
                    this.mUI确认退出畅捷通T零售POS软件吗Text = new WinText(this);
                    #region 搜索条件
                    this.mUI确认退出畅捷通T零售POS软件吗Text.SearchProperties[WinText.PropertyNames.Name] = "确认退出[畅捷通T+零售POS软件]吗？";
                    this.mUI确认退出畅捷通T零售POS软件吗Text.WindowTitles.Add("提示信息");
                    #endregion
                }
                return this.mUI确认退出畅捷通T零售POS软件吗Text;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUI是否手工下载数据Text;
        
        private WinText mUI确认交班吗Text;
        
        private WinText mUI确认退出畅捷通T零售POS软件吗Text;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI畅捷通T零售POS软件Window : WinWindow
    {
        
        public UI畅捷通T零售POS软件Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "畅捷通T+零售POS软件";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("畅捷通T+零售POS软件");
            #endregion
        }
        
        #region Properties
        public WinClient UI畅捷通T零售POS软件Client
        {
            get
            {
                if ((this.mUI畅捷通T零售POS软件Client == null))
                {
                    this.mUI畅捷通T零售POS软件Client = new WinClient(this);
                    #region 搜索条件
                    this.mUI畅捷通T零售POS软件Client.SearchProperties[WinControl.PropertyNames.Name] = "畅捷通T+零售POS软件";
                    this.mUI畅捷通T零售POS软件Client.WindowTitles.Add("畅捷通T+零售POS软件");
                    #endregion
                }
                return this.mUI畅捷通T零售POS软件Client;
            }
        }
        
        public UINoneWindow UINoneWindow
        {
            get
            {
                if ((this.mUINoneWindow == null))
                {
                    this.mUINoneWindow = new UINoneWindow(this);
                }
                return this.mUINoneWindow;
            }
        }
        
        public UIItem1234567890123Window UIItem1234567890123Window
        {
            get
            {
                if ((this.mUIItem1234567890123Window == null))
                {
                    this.mUIItem1234567890123Window = new UIItem1234567890123Window(this);
                }
                return this.mUIItem1234567890123Window;
            }
        }
        
        public UINoneClient UINoneClient
        {
            get
            {
                if ((this.mUINoneClient == null))
                {
                    this.mUINoneClient = new UINoneClient(this);
                }
                return this.mUINoneClient;
            }
        }
        
        public UI输入Window UI输入Window
        {
            get
            {
                if ((this.mUI输入Window == null))
                {
                    this.mUI输入Window = new UI输入Window(this);
                }
                return this.mUI输入Window;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUI畅捷通T零售POS软件Client;
        
        private UINoneWindow mUINoneWindow;
        
        private UIItem1234567890123Window mUIItem1234567890123Window;
        
        private UINoneClient mUINoneClient;
        
        private UI输入Window mUI输入Window;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UINoneWindow : WinWindow
    {
        
        public UINoneWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1006";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("畅捷通T+零售POS软件");
            #endregion
        }
        
        #region Properties
        public WinClient UINoneClient
        {
            get
            {
                if ((this.mUINoneClient == null))
                {
                    this.mUINoneClient = new WinClient(this);
                    #region 搜索条件
                    this.mUINoneClient.SearchProperties[WinControl.PropertyNames.Name] = "none";
                    this.mUINoneClient.WindowTitles.Add("畅捷通T+零售POS软件");
                    #endregion
                }
                return this.mUINoneClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUINoneClient;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItem1234567890123Window : WinWindow
    {
        
        public UIItem1234567890123Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1022";
            this.WindowTitles.Add("畅捷通T+零售POS软件");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("畅捷通T+零售POS软件");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UINoneClient : WinClient
    {
        
        public UINoneClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinControl.PropertyNames.Name] = "none";
            this.WindowTitles.Add("畅捷通T+零售POS软件");
            #endregion
        }
        
        #region Properties
        public WinControl UIP_1Image
        {
            get
            {
                if ((this.mUIP_1Image == null))
                {
                    this.mUIP_1Image = new WinControl(this);
                    #region 搜索条件
                    this.mUIP_1Image.SearchProperties[UITestControl.PropertyNames.Name] = "p_1";
                    this.mUIP_1Image.SearchProperties[UITestControl.PropertyNames.ControlType] = "Image";
                    this.mUIP_1Image.WindowTitles.Add("畅捷通T+零售POS软件");
                    #endregion
                }
                return this.mUIP_1Image;
            }
        }
        
        public WinText 数量合计值
        {
            get
            {
                if ((this.m数量合计值 == null))
                {
                    this.m数量合计值 = new WinText(this);
                    #region 搜索条件
                    this.m数量合计值.SearchProperties[WinText.PropertyNames.Name] = "sum_qty";
                    this.m数量合计值.WindowTitles.Add("畅捷通T+零售POS软件");
                    #endregion
                }
                return this.m数量合计值;
            }
        }
        
        public WinText 数量合计
        {
            get
            {
                if ((this.m数量合计 == null))
                {
                    this.m数量合计 = new WinText(this);
                    #region 搜索条件
                    this.m数量合计.SearchProperties[WinText.PropertyNames.Name] = "sum_qty_t";
                    this.m数量合计.WindowTitles.Add("畅捷通T+零售POS软件");
                    #endregion
                }
                return this.m数量合计;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIP_1Image;
        
        private WinText m数量合计值;
        
        private WinText m数量合计;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI输入Window : WinWindow
    {
        
        public UI输入Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1025";
            this.WindowTitles.Add("畅捷通T+零售POS软件");
            #endregion
        }
        
        #region Properties
        public WinText UI输入Text
        {
            get
            {
                if ((this.mUI输入Text == null))
                {
                    this.mUI输入Text = new WinText(this);
                    #region 搜索条件
                    this.mUI输入Text.SearchProperties[WinText.PropertyNames.Name] = "输入：";
                    this.mUI输入Text.WindowTitles.Add("畅捷通T+零售POS软件");
                    #endregion
                }
                return this.mUI输入Text;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUI输入Text;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI服务器连接设置Window : WinWindow
    {
        
        public UI服务器连接设置Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "服务器连接设置";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("服务器连接设置");
            #endregion
        }
        
        #region Properties
        public UIItemWindow2 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow2(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow2 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1004";
            this.WindowTitles.Add("服务器连接设置");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("服务器连接设置");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1005";
            this.WindowTitles.Add("服务器连接设置");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("服务器连接设置");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI选择账套Window : WinWindow
    {
        
        public UI选择账套Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "选择账套";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("选择账套");
            #endregion
        }
        
        #region Properties
        public UIItemWindow3 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow3(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow12 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow12(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow21 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow21(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItemWindow31 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow31(this);
                }
                return this.mUIItemWindow3;
            }
        }
        
        public UIItemWindow4 UIItemWindow4
        {
            get
            {
                if ((this.mUIItemWindow4 == null))
                {
                    this.mUIItemWindow4 = new UIItemWindow4(this);
                }
                return this.mUIItemWindow4;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow3 mUIItemWindow;
        
        private UIItemWindow12 mUIItemWindow1;
        
        private UIItemWindow21 mUIItemWindow2;
        
        private UIItemWindow31 mUIItemWindow3;
        
        private UIItemWindow4 mUIItemWindow4;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1008";
            this.WindowTitles.Add("选择账套");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("选择账套");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow12 : WinWindow
    {
        
        public UIItemWindow12(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1009";
            this.WindowTitles.Add("选择账套");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("选择账套");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow21 : WinWindow
    {
        
        public UIItemWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1005";
            this.WindowTitles.Add("选择账套");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region 搜索条件
                    this.mUIItemComboBox.WindowTitles.Add("选择账套");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow31 : WinWindow
    {
        
        public UIItemWindow31(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1006";
            this.WindowTitles.Add("选择账套");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region 搜索条件
                    this.mUIItemComboBox.WindowTitles.Add("选择账套");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1007";
            this.WindowTitles.Add("选择账套");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("选择账套");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI交班Window : WinWindow
    {
        
        public UI交班Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "交班";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("交班");
            #endregion
        }
        
        #region Properties
        public UIItemWindow5 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow5(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow5 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow5 : WinWindow
    {
        
        public UIItemWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1002";
            this.WindowTitles.Add("交班");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("交班");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI收银界面esc菜单选择Window : WinWindow
    {
        
        public UI收银界面esc菜单选择Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "菜单选择";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("菜单选择");
            #endregion
        }
        
        #region Properties
        public UINoneClient1 UINoneClient
        {
            get
            {
                if ((this.mUINoneClient == null))
                {
                    this.mUINoneClient = new UINoneClient1(this);
                }
                return this.mUINoneClient;
            }
        }
        #endregion
        
        #region Fields
        private UINoneClient1 mUINoneClient;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UINoneClient1 : WinClient
    {
        
        public UINoneClient1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinControl.PropertyNames.Name] = "none";
            this.WindowTitles.Add("菜单选择");
            #endregion
        }
        
        #region Properties
        public WinEdit 退出收银
        {
            get
            {
                if ((this.m退出收银 == null))
                {
                    this.m退出收银 = new WinEdit(this);
                    #region 搜索条件
                    this.m退出收银.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m退出收银.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m退出收银;
            }
        }
        
        public WinEdit 退货
        {
            get
            {
                if ((this.m退货 == null))
                {
                    this.m退货 = new WinEdit(this);
                    #region 搜索条件
                    this.m退货.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m退货.SearchProperties[WinEdit.PropertyNames.Instance] = "2";
                    this.m退货.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m退货;
            }
        }
        
        public WinEdit 整单赠送
        {
            get
            {
                if ((this.m整单赠送 == null))
                {
                    this.m整单赠送 = new WinEdit(this);
                    #region 搜索条件
                    this.m整单赠送.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m整单赠送.SearchProperties[WinEdit.PropertyNames.Instance] = "3";
                    this.m整单赠送.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m整单赠送;
            }
        }
        
        public WinEdit 商品暂存
        {
            get
            {
                if ((this.m商品暂存 == null))
                {
                    this.m商品暂存 = new WinEdit(this);
                    #region 搜索条件
                    this.m商品暂存.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m商品暂存.SearchProperties[WinEdit.PropertyNames.Instance] = "4";
                    this.m商品暂存.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m商品暂存;
            }
        }
        
        public WinEdit 暂存取货
        {
            get
            {
                if ((this.m暂存取货 == null))
                {
                    this.m暂存取货 = new WinEdit(this);
                    #region 搜索条件
                    this.m暂存取货.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m暂存取货.SearchProperties[WinEdit.PropertyNames.Instance] = "5";
                    this.m暂存取货.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m暂存取货;
            }
        }
        
        public WinEdit 暂存查询
        {
            get
            {
                if ((this.m暂存查询 == null))
                {
                    this.m暂存查询 = new WinEdit(this);
                    #region 搜索条件
                    this.m暂存查询.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m暂存查询.SearchProperties[WinEdit.PropertyNames.Instance] = "6";
                    this.m暂存查询.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m暂存查询;
            }
        }
        
        public WinEdit 对账交款
        {
            get
            {
                if ((this.m对账交款 == null))
                {
                    this.m对账交款 = new WinEdit(this);
                    #region 搜索条件
                    this.m对账交款.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m对账交款.SearchProperties[WinEdit.PropertyNames.Instance] = "7";
                    this.m对账交款.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m对账交款;
            }
        }
        
        public WinEdit 返回
        {
            get
            {
                if ((this.m返回 == null))
                {
                    this.m返回 = new WinEdit(this);
                    #region 搜索条件
                    this.m返回.SearchProperties[WinEdit.PropertyNames.Name] = "b";
                    this.m返回.SearchProperties[WinEdit.PropertyNames.Instance] = "8";
                    this.m返回.WindowTitles.Add("菜单选择");
                    #endregion
                }
                return this.m返回;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit m退出收银;
        
        private WinEdit m退货;
        
        private WinEdit m整单赠送;
        
        private WinEdit m商品暂存;
        
        private WinEdit m暂存取货;
        
        private WinEdit m暂存查询;
        
        private WinEdit m对账交款;
        
        private WinEdit m返回;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI请输入新数量Window : WinWindow
    {
        
        public UI请输入新数量Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "请输入新数量";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("请输入新数量");
            #endregion
        }
        
        #region Properties
        public UIItemWindow6 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow6(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow6 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow6 : WinWindow
    {
        
        public UIItemWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1002";
            this.WindowTitles.Add("请输入新数量");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("请输入新数量");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI现金结算Window : WinWindow
    {
        
        public UI现金结算Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "[现金]结算";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "FNWNS3125";
            this.WindowTitles.Add("[现金]结算");
            #endregion
        }
        
        #region Properties
        public UIItemWindow7 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow7(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow7 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow7 : WinWindow
    {
        
        public UIItemWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1009";
            this.WindowTitles.Add("[现金]结算");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("[现金]结算");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
}
